name: gazebo
channels:
  - conda-forge
# plaforms works on conda-lock https://github.com/conda/conda-lock?tab=readme-ov-file#platform-specification
platforms:
  - win-64
dependencies:
  # Not in vcpkg
  - python=3.9
  - colcon-common-extensions
  - vcstool
  - ruby=3.2  # version in noble
  - pkg-config  # for ogre-next detection in rendering
  - cmake=3.28.3  # version in Noble 
  - dartsim=6.13.2  # version in Noble
  #
  # X stack on Linux
  # - libglu
  # - libglvnd-devel-cos7-x86_64
  # - libwebsockets
  # - mesa-libegl-devel-cos7-x86_64
  # - mesa-libgl-devel-cos7-x86_64
  # - vulkan-headers
  #
  # VCPKG_DEPENDENCIES_LEGACY block:
  - assimp
  - boost-cpp=1.78.0
  - bullet-cpp
  - libccd-double
  #  - console-bridge  #not in conda
  - cppzmq
  - cuda
  - curl
  - dlfcn-win32  # win
  - eigen
  - fcl=0.7.0
  - ffmpeg
  - freeimage
  - gdal
  - gflags
  - glib
  - gts
  - jsoncpp
  - yaml
  - libzip
  - ogre=1.10.12.1
  - ogre-next=2.3.3  # version in Noble
  - openssl
  - protobuf
  - libprotobuf
  - pybind11
  - qt-main
  - qwt
  - libsqlite
  - tinyxml2
  - zeromq
