# Copyright (C) 2024 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
cmake_to_gtest_junit_output.py

This script processes JUnit XML files generated by CTest and injects their full console
standard output (system-out) and error logs directly into the corresponding JUnit XML 
files generated natively by Google Test (gtest) during the same test phase. 

This is particularly useful for CI pipelines (like Jenkins) where gtest output may 
lack critical context for suite-level faults (e.g., segfaults, timeouts, or AddressSanitizer
backtraces) because the testing framework aborted before it could cleanly write them.

By merging the CTest environment logs into the gtest XML outputs, this script ensures:
1. Full CTest output logs are attached directly to any testcases that failed organically.
2. Suite-level crashes safely increment failure counters and automatically spawn a 
   synthetic <testcase> node holding the crash backtrace and full system-out log, 
   ensuring the crash is tracked and easily clickable in the CI Test Results UI.
"""

import argparse
import copy
import os
import sys
from xml.etree import ElementTree as ET

SYSTEM_OUT_TAG = "system-out"


def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser(
        description="Parse system output from junit file generated by CTest"
                    "and inject it into existing junit files generated "
                    "by gtest. Useful in some cases like ASAN reports."
    )
    parser.add_argument(
        "cmake_junit_file",
        help="Junit file generated by 'cmake --output-junit=<cmake_junit_file>'",
    )
    parser.add_argument(
        "gtest_results_dir",
        help="Directory where gtest junit files were output"
    )
    args = parser.parse_args(argv)

    # Parse the CTest-generated JUnit XML. This file acts as the baseline 'source'
    # of truth for overall executable status and contains the raw console outputs.
    doc = ET.parse(args.cmake_junit_file)

    for testcase in doc.findall("testcase"):
        # Ignore tests that start with 'check_'. Those are tests that simply
        # run the check_test_run.py script, so we don't need their output.
        if testcase.attrib["name"].startswith("check_"):
            continue

        results_file_name = os.path.join(
            args.gtest_results_dir, testcase.attrib["name"] + ".xml"
        )
        system_output = testcase.find(SYSTEM_OUT_TAG)
        testcase_failures = 0
        assert system_output is not None
        try:
            print(f"Processing {results_file_name}")
            results_doc = ET.parse(results_file_name)
            root = results_doc.getroot()
            should_write_to_file = False
            
            ctest_failed = testcase.attrib.get("status") == 'fail'
            
            # 1. Update testcase failures and inject system-out into existing natively failed testcases
            has_native_failures = False
            for tc in results_doc.findall(".//testcase"):
                if tc.find("failure") is not None or tc.find("error") is not None:
                    has_native_failures = True
                    if tc.find(SYSTEM_OUT_TAG) is None:
                        tc.append(copy.deepcopy(system_output))
                        should_write_to_file = True

            # Locate the primary <testsuite> tag to append any synthetic testcase nodes.
            # Normal gtest files have a <testsuites> root with <testsuite> children, but 
            # fallback XML files generated by check_test_run.py start directly with <testsuite>.
            target_testsuite = root if root.tag == "testsuite" else root.find("testsuite")

            if ctest_failed:
                print(f" - inject error for CTest suite failure in {testcase.attrib.get('name', 'unknown')}")
                if target_testsuite is not None:
                    # Increment the failure count for the testsuite by exactly 1 to cleanly 
                    # account for the suite-level CTest crash without squashing existing failures.
                    current_fails = int(target_testsuite.attrib.get('failures', 0))
                    target_testsuite.attrib['failures'] = str(current_fails + 1)

                    # Create a synthetic testcase to officially house the error and log in the CI dashboard
                    synth_tc = ET.Element("testcase", {
                        "name": "CTest_Failure_Log",
                        "classname": target_testsuite.attrib.get("name", "CTest"),
                        "time": "0.0"
                    })
                    
                    error_tag = ET.Element('error', {'message':
                        f'Failure injected from CTest by tools/{os.path.basename(__file__)}'})
                    error_tag.text = system_output.text
                    synth_tc.append(error_tag)
                    synth_tc.append(copy.deepcopy(system_output))
                    
                    target_testsuite.append(synth_tc)
                    should_write_to_file = True

                if root.tag == "testsuites":
                    # Similarly increment the root-level aggregate counter
                    root_fails = int(root.attrib.get('failures', 0))
                    root.attrib["failures"] = str(root_fails + 1)
                    should_write_to_file = True

            elif not has_native_failures and target_testsuite is not None:
                # If CTest passed and there were absolutely no gtest failures either, 
                # we still create a single dummy testcase to hold the full log simply 
                # so the developer has a clickable link in Jenkins to review standard output.
                print(f" - inject system-out for CTest execute in {testcase.attrib.get('name', 'unknown')}")
                synth_tc = ET.Element("testcase", {
                    "name": "CTest_Execution_Log",
                    "classname": target_testsuite.attrib.get("name", "CTest"),
                    "time": "0.0"
                })
                synth_tc.append(copy.deepcopy(system_output))
                target_testsuite.append(synth_tc)
                should_write_to_file = True

            if should_write_to_file:
                results_doc.write(results_file_name, xml_declaration=True, encoding="UTF-8")

        except Exception as e:
            print(e) if str(e).startswith('[Errno 2]') else exit(1)

    print("""
      Possible failures above in the script are expected due to:
      - Tests written directly in CTest and not using gtest
        (INTEGRATION_versioned_symbols as an example)
      - Tests in Python using pytest have different name:
        right name in CTest vs filepath name in current setup
      """)

if __name__ == "__main__":
    main()
