#!/bin/bash -x

export ROS_DISTRO=melodic

export GPU_SUPPORT_NEEDED=true
# the tarball shipped by subt is generated by catkin_make and not compatible
# to be reused by catkin tools
export USE_CATKIN_MAKE=true

# Do not use the subprocess_reaper in debbuild. Seems not as needed as in
# testing jobs and seems to be slow at the end of jenkins jobs
export ENABLE_REAPER=false

DOCKER_JOB_NAME="subt_ci"
. ${SCRIPT_DIR}/lib/boilerplate_prepare.sh
. ${SCRIPT_DIR}/lib/_gazebo_utils.sh
. ${SCRIPT_DIR}/lib/_subt_utils.sh

# Needs pointgrey SDK (manual installation) and downloader is broken from ros-drivers.
# manual installation from our nodes
if [[ ! -d /var/lib/jenkins/.pointgrey_sdk ]]; then
    echo 'The node has not been setup for pointgrey sdk'
    exit 1
fi

mkdir -p "${WORKSPACE}/pointgrey/"
for f in libflycapture-2.13.3.31_amd64.deb libflycapture-2.13.3.31_amd64-dev.deb; do
  cp "/var/lib/jenkins/.pointgrey_sdk/$f" "${WORKSPACE}/pointgrey/"
done

# husky and jackal descriptions are used
# Models are used in tests
export ROS_WS_PREBUILD_HOOK="""
# Install pointgrey sdk
dpkg -i ${WORKSPACE}/pointgrey/libflycapture-2.13.3.31_amd64.deb
dpkg -i ${WORKSPACE}/pointgrey/libflycapture-2.13.3.31_amd64-dev.deb
rm -fr ${WORKSPACE}/subt/husky_description ${WORKSPACE}/subt/pointgrey_camera_driver ${WORKSPACE}/subt/jackal_description
git clone --depth 1 https://github.com/husky/husky.git /tmp/huksy > /dev/null
git clone --depth 1 https://github.com/jackal/jackal.git /tmp/jackal > /dev/null
git clone --depth 1 https://github.com/ros-drivers/pointgrey_camera_driver /tmp/pointgrey_camera_driver > /dev/null
mv /tmp/huksy/husky_description ${WORKSPACE}/subt/
mv /tmp/jackal/jackal_description  ${WORKSPACE}/subt/
mv /tmp/pointgrey_camera_driver ${WORKSPACE}/subt/
${GAZEBO_MODEL_INSTALLATION}
"""

(
set -o errexit
# if execute with bash instead of source, lost colors on Jenkins. SAD.
source ${SCRIPT_DIR}/lib/_ros_setup_buildsh.bash "subt"
)

DEPENDENCY_PKGS="${DEPENDENCY_PKGS} ${SUBT_DEPENDENCIES} psmisc"
# ROS packages come from the mirror in the own subt repository
USE_ROS_REPO=true
OSRF_REPOS_TO_USE="stable"

. ${SCRIPT_DIR}/lib/docker_generate_dockerfile.bash
. ${SCRIPT_DIR}/lib/docker_run.bash
