#!/bin/bash -x

export ROS_DISTRO=melodic

export GPU_SUPPORT_NEEDED=true
# the tarball shipped by subt is generated by catkin_make and not compatible
# to be reused by catkin tools
export USE_CATKIN_MAKE=true

# Do not use the subprocess_reaper in debbuild. Seems not as needed as in
# testing jobs and seems to be slow at the end of jenkins jobs
export ENABLE_REAPER=false

DOCKER_JOB_NAME="subt_ci"
. ${SCRIPT_DIR}/lib/boilerplate_prepare.sh
. ${SCRIPT_DIR}/lib/_gazebo_utils.sh
. ${SCRIPT_DIR}/lib/_subt_utils.sh

# Need special tarball
# see: https://bitbucket.org/osrf/subt/wiki/tutorials/ExampleSetup
# remove subt_example and subt_gazebo since there are coming from the repo under testing
# Models are used in tests
export ROS_WS_PREBUILD_HOOK="""
${GAZEBO_MODEL_INSTALLATION}

git clone --depth 1 https://github.com/husky/husky.git /tmp/huksy
git clone --depth 1 https://github.com/jackal/jackal.git /tmp/jackal
mv /tmp/husky/husky_description ${WORKSPACE}/subt/
mv /tmp/jackal/jackal_description ${WORKSPACE}/subt/
"""

export ROS_SETUP_POSTINSTALL_HOOK="""
echo '# BEGIN SECTION: smoke test'
source ./install/setup.bash || true
${SUBT_COMPETITION_TEST}
echo 'Smoke testing completed successfully.'
echo '# END SECTION'
"""

# Generate the first part of the build.sh file for ROS
. ${SCRIPT_DIR}/lib/_ros_setup_buildsh.bash "subt"

DEPENDENCY_PKGS="${SUBT_DEPENDENCIES} psmisc"
# ROS packages come from the mirror in the own subt repository
USE_ROS_REPO=true
OSRF_REPOS_TO_USE="stable"

. ${SCRIPT_DIR}/lib/docker_generate_dockerfile.bash
. ${SCRIPT_DIR}/lib/docker_run.bash
