#!/bin/bash -x

case ${DISTRO} in
  'kinetic')
    ROS_DISTRO=melodic
    GAZEBO_VERSION_FOR_ROS="9"
    ;;
  'bionic')
    # 9 is the default version in Bionic
    ROS_DISTRO=melodic
    USE_DEFAULT_GAZEBO_VERSION_FOR_ROS=true
    ;;
  *)
    echo "Unsupported DISTRO: ${DISTRO}"
    exit 1
esac

export GPU_SUPPORT_NEEDED=true
# the tarball shipped by vrx is generated by catkin_make and not compatible
# to be reused by catkin tools
export USE_CATKIN_MAKE=true

# Do not use the subprocess_reaper in debbuild. Seems not as needed as in
# testing jobs and seems to be slow at the end of jenkins jobs
export ENABLE_REAPER=false

DOCKER_JOB_NAME="vrx_ci"
. ${SCRIPT_DIR}/lib/boilerplate_prepare.sh

export ROS_SETUP_POSTINSTALL_HOOK="""
echo '# BEGIN SECTION: smoke test'

killall gazebo gzserver || true

source ./install/setup.bash || true

TEST_TIMEOUT=180
TEST_START=\$(date +%s)
timeout --preserve-status \$TEST_TIMEOUT roslaunch vrx_gazebo sandisland.launch extra_gazebo_args:=\"--verbose\"
TEST_END=\$(date +%s)
DIFF=\$(expr \$TEST_END - \$TEST_START)

if [ \$DIFF -lt \$TEST_TIMEOUT ]; then
  echo \"The test took less than \$TEST_TIMEOUT. Something bad happened.\"
  Typo
  exit 1
fi

echo 'Smoke testing completed successfully.'
echo '# END SECTION'
"""

# Generate the first part of the build.sh file for ROS
. ${SCRIPT_DIR}/lib/_ros_setup_buildsh.bash "vrx"

DEPENDENCY_PKGS="git ruby libeigen3-dev pkg-config python ros-${ROS_DISTRO}-gazebo-plugins ros-${ROS_DISTRO}-gazebo-ros ros-${ROS_DISTRO}-hector-gazebo-plugins ros-${ROS_DISTRO}-joy ros-${ROS_DISTRO}-joy-teleop ros-${ROS_DISTRO}-key-teleop ros-${ROS_DISTRO}-robot-localization ros-${ROS_DISTRO}-robot-state-publisher ros-${ROS_DISTRO}-rviz ros-${ROS_DISTRO}-ros-base ros-${ROS_DISTRO}-teleop-tools ros-${ROS_DISTRO}-teleop-twist-keyboard ros-${ROS_DISTRO}-velodyne-simulator ros-${ROS_DISTRO}-xacro ros-${ROS_DISTRO}-rqt ros-${ROS_DISTRO}-rqt-common-plugins protobuf-compiler"

# ROS packages come from the mirror in the own vrx repository
USE_ROS_REPO=true

. ${SCRIPT_DIR}/lib/docker_generate_dockerfile.bash
. ${SCRIPT_DIR}/lib/docker_run.bash
