#!/bin/bash -x

# Knowing Script dir beware of symlink
[[ -L ${0} ]] && SCRIPT_LIBDIR=$(readlink ${0}) || SCRIPT_LIBDIR=${0}
SCRIPT_LIBDIR="${SCRIPT_LIBDIR%/*}"

set -e

# directory to find the .json file generated by brew-bot with the hash
# TODO: send the directory from the DSL
BOTTLE_JSON_DIR=${WORKSPACE}/pkgs

echo '# BEGIN SECTION: check variables'
if [ -z "${ghprbCommentBody}" ]; then
    echo ghprbCommentBody not specified
    exit -1
fi
if [ -z "${PULL_REQUEST_URL}" ]; then
  echo PULL_REQUEST_URL not specified
  exit -1
fi
PULL_REQUEST_API_URL=$(echo ${PULL_REQUEST_URL} \
  | sed -e 's@^https://github\.com/@https://api.github.com/repos/@' \
        -e 's@/pull/\([0-9]\+\)/*$@/pulls/\1@')
PULL_REQUEST_HEAD_REPO=$(curl ${PULL_REQUEST_API_URL} \
  | python3 -c 'import json, sys; print(json.loads(sys.stdin.read())["head"]["repo"]["ssh_url"])')
PULL_REQUEST_BRANCH=$(curl ${PULL_REQUEST_API_URL} \
  | python3 -c 'import json, sys; print(json.loads(sys.stdin.read())["head"]["ref"])')
if [[ "${ghprbCommentBody}" =~ 'brew-bot-tag:' ]]; then
  if [[ "${ghprbCommentBody}" =~ 'build-for-new-distro-' ]]; then
    export KEEP_OLD=--keep-old
  fi
fi
echo '# END SECTION'

# note that matrix projects use subdirectories on pkgs/ with the label of different configurations
FILES_WITH_NEW_HASH="$(find ${BOTTLE_JSON_DIR} -name '*.json')"

# call to github setup
. ${SCRIPT_LIBDIR}/_homebrew_github_setup.bash

if [ -z "${TAP_PREFIX}" ]; then
	echo TAP_PREFIX not specified
	exit -1
fi

echo "# BEGIN SECTION: update bottle hashes"

brew bottle --merge --write --no-commit ${KEEP_OLD} ${FILES_WITH_NEW_HASH}

# ensure that all modified files are committed
export FORMULA_PATH='-a'

echo '# END SECTION'

COMMIT_MESSAGE="update bottle"
SKIP_COMMIT=false
. ${SCRIPT_LIBDIR}/_homebrew_github_commit.bash
