# Copyright 2025 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was generated by Gemini 2.5 Pro.

"""
Provides functionality to interact with the GitHub GraphQL API to fetch user data.
"""

import json
import subprocess
import re
from PIL import Image, ImageDraw, ImageOps

AVATAR_SIZE = 256  # The size (width/height) for each avatar in the collage

def build_graphql_query(usernames: list[str]) -> str:
    """
    Constructs a single GraphQL query to fetch multiple users by login.

    Args:
        usernames: A list of GitHub usernames.

    Returns:
        A formatted GraphQL query string.
    """
    query_parts = []
    for username in usernames:
        alias = "user_" + re.sub(r'[^a-zA-Z0-9_]', '_', username)
        query_parts.append(f"""
            {alias}: user(login: "{username}") {{
                name
                login
                url
                avatarUrl(size: {AVATAR_SIZE})
            }}
        """)
    
    return f"query GetContributors {{ {' '.join(query_parts)} }}"

def fetch_contributors_gh_cli(query: str) -> dict | None:
    """
    Sends a query to the GitHub GraphQL API using the 'gh' CLI tool.

    Args:
        query: The GraphQL query string.

    Returns:
        A dictionary containing the user data from the API, or None on error.
    """
    command = ["gh", "api", "graphql", "-f", f"query={query}"]
    try:
        process = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True,
            encoding='utf-8'
        )
        result = json.loads(process.stdout)
        if "errors" in result:
            print(f"❌ GraphQL API returned errors: {result['errors']}")
            return None
        return result.get("data")
    except FileNotFoundError:
        print("❌ Error: The 'gh' command-line tool is not installed or not in your PATH.")
        print("   Please install it from https://cli.github.com/ and authenticate with 'gh auth login'.")
        return None
    except subprocess.CalledProcessError as e:
        print("⚠️  Error executing 'gh' command. Is 'gh auth login' configured?")
        print(f"   Stderr: {e.stderr}")
        return None
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing JSON response from 'gh' CLI: {e}")
        return None