[project]
name = "gazebo"
version = "0.1.0"
description = "Pixi configuration to run Gazebo Jetty. Similar versions than Ubuntu Noble."
authors = ["Jose Luis Rivero <jrivero@openrobotics.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64"]

[dependencies]
assimp = "*"
bullet-cpp = "3.25.*"        # compatible with dart, good for noble
cli11 = ">=2.4.1,<3"
cppzmq = "*"
curl = "*"
dartsim = "6.13.*"           # good for noble
eigen = "3.4.0.*"            # good for noble
ffmpeg = "*"
freeimage = "*"
gdal = "3.*"
gflags = "*"
jsoncpp = "*"
libprotobuf = "*"
libsqlite = "*"
libzip = "*"
ogre = "1.10.12.1.*"
ogre-next = "2.3.*"
openssl = "*"
protobuf = "*"
pybind11 = "*"
python = "3.12.*"
qt6-main = "6.8.*"
ruby = "*"
tinyxml2 = "*"
yaml = "*"
zeromq = "4.3.4.*"           # good for noble
libwebsockets = ">=4.3.3,<5" # good for noble
libzenohc = ">=1.3.0,<2"
libzenohcxx = ">=1.3.0,<2"

[target.win-64.dependencies]
dlfcn-win32 = "*"
vs2019_win-64 = ">=19.29.30139,<20"

[target.linux.dependencies]
libegl-devel = "*"
libgl-devel = "*"
libglu = "*"
libglvnd-devel = "*"

[target.linux-64.dependencies]
libwebsockets = "*"
vulkan-headers = "*"

[build-dependencies]
cmake = "3.28.3.*"  # good on noble
colcon-common-extensions = "*"
pkg-config = "*"
vcstool = "*"
