name: Conda env testing

on:
  pull_request:
  push:

jobs:
  detection:
    runs-on: ubuntu-latest
    outputs:
      toml_file: ${{ steps.changed-toml-files.outputs.toml_file }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Detect changed files
      shell: bash
      id: changed-files
      run: |
        if [ "${{ github.event.pull_request }}" != "" ]; then
          # Pull request
          ALL_CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr '\n' ' ')
        else
          # Not a pull request
              ALL_CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
        fi
        echo $ALL_CHANGED_FILES
        echo "all_changed_files=$ALL_CHANGED_FILES" >> $GITHUB_OUTPUT
    - name: List all changed files
      id: changed-toml-files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        ALL_TOML_FILES=""
         for file in ${ALL_CHANGED_FILES}; do
           if [[ $file == *.toml ]]; then
             ALL_TOML_FILES="$ALL_TOML_FILES $file"
           fi
         done
         ALL_TOML_FILES=${ALL_TOML_FILES# }
         echo "All TOML files: ${ALL_TOML_FILES}"
         echo "${ALL_TOML_FILES}" >> $GITHUB_OUTPUT
  pixi_builder:
    name: Pixi builder
    needs: detection
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.detection.outputs.toml_file) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies using pixi on ${{ matrix.toml_file }}
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659  # v0.8.1
        with:
          locked: true
          cache: false  # 10Gb limit might be too low for caching
          manifest-path: ${{ matrix.toml_file }}
