name: DSL logs and checks

on:
  pull_request:
  push:
    paths:
      - 'conda/envs/legacy/**'

jobs:
  legacy_pixi_test:
    runs-on: ubuntu-latest
    name: Legacy testing Pixi
    steps:
      - name: Install pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659  # v0.8.1
        with:
          locked: true
          cache: false  # 10Gb limit might be too low for caching
      - name: Build Gazebo enviroment
        run:
          pixi install --locked --manifest-path conda/envs/legacy/
