name: Releasing tests

on:
  push:
    paths:
      - release.py
      - check_releasepy.bash
      - jenkins-scripts/dsl/gz-collections.yaml
      - jenkins-scripts/dsl/tools/get_collections_from_package_and_version.py

jobs:
  dsl_ci:
    runs-on: ubuntu-latest
    name: release.py checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run release.py script tests
        run: ./check_releasepy.bash
